# Site settings
author: Alice Kwon
title: 
header-img: img/home-bg.png
email: akwon@gradcenter.cuny.edu
copyright_name: Alice Kwon
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  akwon100

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
